[package]
name = "client"
version = "0.1.0"
authors = ["Mark Benvenuto <mark.benvenuto@mongodb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocol = {path="../protocol"}
kmip_client = {path="../kmip_client"}

structopt = "0.3.5"
clap-verbosity-flag = "0.3.0"
clap-log-flag = "0.2.1"
log= "0.4.8"
env_logger= "0.7.1"

confy = "0.3.1"

pretty-hex = "0.1.1"

rustls = "0.16.0"
mio = "0.6.21"

webpki = "0.21.0"

