[package]
name = "client"
version = "0.1.0"
authors = ["Mark Benvenuto <mark.benvenuto@mongodb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocol = {path="../protocol"}

structopt = "0.2.18"
clap-verbosity-flag = "0.2.0"
clap-log-flag = "0.2.1"
log= "0.4.7"
env_logger= "0.6.2"

confy = "0.3.1"



rustls = "0.15.2"
mio = "0.6.19"

# use older verion
webpki = "0.19.0"

webpki-roots = "0.16.0"
