[package]
name = "client"
authors = ["Mark Benvenuto <mark.benvenuto@mongodb.com>"]
license = "Apache-2.0"
version.workspace = true
edition.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap  = { workspace = true }
clap-log-flag  = { workspace = true }
clap-verbosity-flag  = { workspace = true }
confy  = { workspace = true }
hex  = { workspace = true }
kmip_client  = { workspace = true }
mio  = { workspace = true }
pretty-hex  = { workspace = true }
protocol  = { workspace = true }
rustls  = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
webpki  = { workspace = true }
webpki-roots  = { workspace = true }
