[package]
name = "kmip"
version = "0.1.0"
authors = ["Mark Benvenuto <mark.benvenuto@mongodb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ttlv = {path="ttlv"}

byteorder = "1.3.2"

serde = "1.0.94"
serde_derive = "1.0.94"
pretty-hex = "0.1.0"
serde-transcode = "1.1.0"
serde_json = "1.0.40"

structopt = "0.2.18"
clap-verbosity-flag = "0.2.0"
clap-log-flag = "0.2.1"
log= "0.4.7"
env_logger= "0.6.2"

confy = "0.3.1"

num = "0.2.0"
num-traits = "0.2"
num-derive = "0.2.5"


rustls = "0.15.2"

mio = "0.6.19"

vecio = "0.1.0"

strum = "0.15.0"
strum_macros = "0.15.0"


