[package]
name = "tests_e2e"
version = "0.1.0"
authors = ["Mark Benvenuto <mark.benvenuto@mongodb.com>"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { workspace = true }
difference = { workspace = true }
hex  = { workspace = true }
kmip_client = { workspace = true }
kmip_server  = { workspace = true }
lazy_static  = { workspace = true }
protocol = { workspace = true }
quick-xml  = { workspace = true }
regex = { workspace = true }
rustls  = { workspace = true }
tracing = { workspace = true }
ttlv = { workspace = true }
webpki  = { workspace = true }
webpki-roots  = { workspace = true }
