[package]
name = "protocol"
version = "0.1.0"
authors = ["Mark Benvenuto <mark.benvenuto@mongodb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_enum = {path="../serde_enum"}

serde = "1.0.104"
serde_derive = "1.0.104"
serde_bytes = "0.11.3"

num = "0.2.0"
num-traits = "0.2"
num-derive = "0.3.0"

strum = "0.17.0"
strum_macros = "0.17.0"

chrono = { version = "0.4.10", features = ["serde"] }

log = "0.4.8"

byteorder = "1.3.2"

pretty-hex = "0.1.1"

failure = "0.1.6"
failure_derive = "0.1.6"
