[package]
name = "protocol"
version = "0.1.0"
authors = ["Mark Benvenuto <mark.benvenuto@mongodb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ttlv = {path="../ttlv"}
serde_enum = {path="../serde_enum"}

serde = "1.0.97"
serde_derive = "1.0.97"
serde_bytes = "0.11.1"


num = "0.2.0"
num-traits = "0.2"
num-derive = "0.2.5"

strum = "0.15.0"
strum_macros = "0.15.0"

chrono = { version = "0.4.7", features = ["serde"] }

