[package]
name = "kmip_server"
authors = ["Mark Benvenuto <mark.benvenuto@mongodb.com>"]
license = "Apache-2.0"
version.workspace = true
edition.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes  = { workspace = true }
cbc  = { workspace = true }
ecb  = { workspace = true }
crypto-common  = { workspace = true }
block-padding  = { workspace = true }
aws-lc-rs = { workspace = true }
bson  = { workspace = true }
byteorder  = { workspace = true }
chrono  = { workspace = true }
clap  = { workspace = true }
clap-log-flag  = { workspace = true }
clap-verbosity-flag  = { workspace = true }
confy  = { workspace = true }
digest  = { workspace = true }
futures  = { workspace = true }
hmac  = { workspace = true }
lazy_static  = { workspace = true }
mio  = { workspace = true }
mongodb  = { workspace = true }
num  = { workspace = true }
num-derive  = { workspace = true }
num-traits  = { workspace = true }
pretty-hex  = { workspace = true }
protocol = { workspace = true }
rustls  = { workspace = true }
serde  = { workspace = true }
serde_derive  = { workspace = true }
sha2  = { workspace = true }
strum  = { workspace = true }
strum_macros  = { workspace = true }
thiserror  = { workspace = true }
tokio  = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
ttlv  = { workspace = true }
vecio  = { workspace = true }
webpki-roots  = { workspace = true }
