[package]
name = "kmip_server"
authors = ["Mark Benvenuto <mark.benvenuto@mongodb.com>"]
license = "Apache-2.0"
version.workspace = true
edition.workspace = true
publish = false

[package.metadata.cargo-machete]
ignored = ["num-traits", "strum"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes  = { workspace = true }
aws-lc-rs = { workspace = true }
block-padding  = { workspace = true }
bson  = { workspace = true }
cbc  = { workspace = true }
chrono  = { workspace = true }
clap  = { workspace = true }
clap-verbosity-flag  = { workspace = true }
crypto-common  = { workspace = true }
digest  = { workspace = true }
ecb  = { workspace = true }
futures  = { workspace = true }
hmac  = { workspace = true }
kmip_protocol = { workspace = true }
lazy_static  = { workspace = true }
mongodb  = { workspace = true }
pretty-hex  = { workspace = true }
rustls  = { workspace = true }
serde  = { workspace = true }
sha2  = { workspace = true }
strum = { workspace = true }
strum_macros  = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
ttlv  = { workspace = true }
webpki-roots  = { workspace = true }
