[package]
name = "ttlv"
authors = ["Mark Benvenuto <mark.benvenuto@mongodb.com>"]
license = "Apache-2.0"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
byteorder = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
hex = { workspace = true }
num = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
pretty-hex = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
ttlv_derive = { workspace = true }
xml = { workspace = true }
