[package]
name = "kmip_protocol"
authors = ["Mark Benvenuto <mark.benvenuto@mongodb.com>"]
license = "Apache-2.0"
version.workspace = true
edition.workspace = true
publish = false

[package.metadata.cargo-machete]
ignored = ["num-traits", "serde", "strum"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { workspace = true, features = ["serde"] }
num = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde  = { workspace = true }
serde_derive  = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
ttlv = { workspace = true }
